<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ConsoleControl.Core/ConsoleControl.Core.csproj" />
    <PackageReference Include="SDL3-CS" Version="3.4.14.1" />
    <PackageReference Include="SDL3-CS.Linux" Version="3.4.14.1" />
  </ItemGroup>
</Project>
